development:
  adapter: postgresql
  encoding: unicode
  database: brewmasters_development
  pool: 5
  username: gt565k
  password: 
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: brewmasters_test
  pool: 5
  username: gt565k
  password: 
  min_messages: WARNING